FROM node:4

WORKDIR /home/app_thai/api_rest

EXPOSE 8082

# install packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y \
        git && \
    apt-get clean && apt-get autoclean

# execute repo script
COPY ./run.sh /home/app_thai/api_rest/run.sh
RUN chmod +x /home/app_thai/api_rest/run.sh
CMD ["/home/app_thai/api_rest/run.sh"]

#CMD ["node", "app.js"]